call pathogen#infect()
syntax on
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on

set nocompatible
set modelines=0
set encoding=utf-8

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=85

augroup cline
    au!
    au WinLeave,InsertEnter * set nocursorline
    au WinEnter,InsertLeave * set cursorline
augroup END

set visualbell
set showmode
set showcmd
set hidden
set cursorline
set ruler
set backspace=indent,eol,start
set laststatus=2

set list
set listchars=tab:▸\ ,eol:¬

set wildmenu
set wildmode=list:longest
set wildignore+=.git
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest
set wildignore+=*.DS_Store
set wildignore+=*.pyc

colorscheme badwolf

let g:Powerline_symbols = 'fancy'
let g:Powerline_cache_enabled = 1

let mapleader = ","

" }}}
 augroup ft_python
     au!

     au FileType python setlocal define=^\s*\\(def\\\\|class\\)
     au FileType man nnoremap <buffer> <cr> :q<cr>
     " Jesus tapdancing Christ, built-in Python syntax, you couldn't let me
     " override this in a normal way, could you?
     au FileType python if exists("python_space_error_highlight") | unlet python_space_error_highlight | endif
     " Jesus, Python.  Five characters of punctuation for a damn string?
     au FileType python inoremap <buffer> <c-g> _(u'')<left><left>
     au FileType python inoremap <buffer> <c-b> """"""<left><left><left>
augroup END


noremap H ^
noremap L $

nnoremap <leader>w <C-w>v<C-w>l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

noremap  <F2> :NERDTreeToggle<cr>
inoremap <F2> <esc>:NERDTreeToggle<cr>

set backup                        " enable backups
set noswapfile                    " It's 2012, Vim.
set undodir=~/.vim/tmp/undo/     " undo files
set backupdir=~/.vim/tmp/backup/ " backups
set directory=~/.vim/tmp/swap/   " swap files

 " Make those folders automatically if they don't already exist.
if !isdirectory(expand(&undodir))
    call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
    call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
    call mkdir(expand(&directory), "p")
endif

nnoremap ; :

inoremap jk <ESC>

